spring.application.name=samrat
spring.datasource.url=jdbc:mysql://localhost:3306/samrat
spring.datasource.username=root
spring.datasource.password=samrat@1616
spring.jpa.hibernate.ddl-auto=update

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# JWT Configuration
app.jwt.secret=HMS_ENTERPRISE_SECRET_KEY_FOR_JWT_32_CHAR_MIN_HMS_HMS
app.jwt.expiration=86400000

# Logging
logging.level.org.springframework.security=DEBUG
logging.level.com.example.samrat=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.level.org.springframework.orm.jpa=DEBUG
logging.level.org.springframework.transaction=DEBUG

# Server Port
server.port=5001

# SpringDoc OpenAPI Configuration
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.packages-to-scan=com.example.samrat
springdoc.paths-to-match=/**
springdoc.show-actuator=true
springdoc.swagger-ui.operations-sorter=alpha
springdoc.swagger-ui.tags-sorter=alpha
springdoc.swagger-ui.doc-expansion=none
springdoc.writer-with-default-pretty-printer=true
